server:
  port: 8800
# spring
spring:
  application:
    name: edpglobal-config-server
  main:
    banner-mode: 'off'
  profiles:
    active:
    - jdbc
#    - git
  cloud:
    config:
      server:
        git: 
          uri: http://10.32.15.89/edpglobal/datahub-springcloud-config.git/
          username: cfuser
          password: 1qaz2wsx-pl,
          search-paths: '{application}'
        jdbc:
          sql: SELECT `key`, `value` FROM `properties` WHERE `application`=? AND `profile`=? AND `label`=?
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.32.15.91:3306/edpglobal_config_server?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: edpuser
    password: oawLaWSL@1
    druid:
      # 验证连接是否有效。此参数必须设置为非空字符串，下面三项设置成true才能生效
      validation-query: SELECT 1
      # 连接是否被空闲连接回收器(如果有)进行检验. 如果检测失败, 则连接将被从池中去除
      test-while-idle: true
      # 是否在从池中取出连接前进行检验, 如果检验失败, 则从池中去除连接并尝试取出另一个
      test-on-borrow: true
      # 是否在归还到池中前进行检验
      test-on-return: false
      # 连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
  rabbitmq:
    host: 10.32.15.101
    port: 32066
    username: admin
    password: admin123
    virtual-host: /datahub_vhost
  http:
    encoding:
      charset: UTF-8
# management
management:
  endpoints:
    web:
      exposure:
        include: '*'
# logging
logging:
  path: /edpglobal/logs/${spring.application.name}
  level:
    root: info
# eureka
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://datahub.eureka.node1.com:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3
